# Generated by Django 3.2.6 on 2021-12-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
