# Generated by Django 3.2.6 on 2021-12-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20211207_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='funcao',
            field=models.CharField(choices=[('admin', 'Admin'), ('municipio', 'Município'), ('gerencia', 'Gerência'), ('padrao', 'Padrão')], max_length=50),
        ),
    ]
