# Generated by Django 3.2.6 on 2021-12-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='funcao',
            field=models.CharField(choices=[('admin', 'Admin'), ('municipio', 'Município'), ('gerencia', 'Gerência'), ('padrao', 'Padrão')], default='padrao', max_length=50),
        ),
    ]
