version: "3.3"

services:

  web:
    build: .
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/sisgevs_docker
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8001:5432
    volumes:
      - ./dados/sql_insert/insert_dados.sql:/insert/insert.sql
      - ./dados/sql_insert/test.sql:/insert/test.sql
      - postgres_data:/var/lib/postgresql/data/      

volumes:
  postgres_data: