version: "3.3"

services:

  web:
    build: .
    command: sh -c 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/sisgevs_docker
    ports:
      - 8001:8000
    depends_on:
      - db
  
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8002:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/      

volumes:
  postgres_data: