# Generated by Django 3.2.6 on 2021-10-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiao',
            name='descricao',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
