# Generated by Django 3.2.6 on 2021-10-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_regiao_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoIbge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio')),
            ],
            options={
                'verbose_name': 'ibge',
                'verbose_name_plural': 'ibges',
                'ordering': ('codigo',),
            },
        ),
    ]
