# Generated by Django 3.2.6 on 2021-10-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_codigoibge'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinMunicipioIbgeUnidadeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.codigoibge')),
                ('municipio_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.municipio')),
                ('unidade_saude_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidadesaude')),
            ],
        ),
    ]
