# Generated by Django 3.2.6 on 2021-11-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211027_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoesporotricose',
            name='unidade_saude_outro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
