# Generated by Django 3.2.6 on 2021-11-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_casoesporotricose_unidade_saude_outro'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoesporotricose',
            name='gerencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.gerencia'),
        ),
        migrations.AlterField(
            model_name='casoesporotricose',
            name='municipio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
