# Generated by Django 3.2.6 on 2021-11-12 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipioBr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True)),
                ('uf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
            ],
        ),
        migrations.CreateModel(
            name='JoinDistritoMunicipioIbgeEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.distrito')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estado')),
                ('ibge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.codigoibge')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.municipiobr')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.municipiobr'),
        ),
    ]
