# Generated by Django 3.2.6 on 2021-11-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211112_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipiobr',
            name='ibge',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
