# Generated by Django 3.2.6 on 2021-11-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211118_1316'),
        ('core', '0012_municipios'),
    ]

    operations = [
    ]
