insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão da Décima primeira região', '11', '1', '3', '11ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '2', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values (' Renascer do Brejo', '3', '3', '2', '3ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values (' Renascer do Brejo', '3', '4', '2', '3ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '5', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '6', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values (' Renascer do Brejo', '3', '7', '2', '3ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '8', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '9', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale dos Dinossauros', '10', '10', '3', '10ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '11', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values (' Renascer do Brejo', '3', '12', '2', '3ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '13', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values (' Renascer do Brejo', '3', '14', '2', '3ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '15', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values (' Renascer do Brejo', '3', '16', '2', '3ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '17', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '18', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Mamanguape', '1', '19', '1', '14ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '20', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Curimataú e Seridó Paraibano', '4', '21', '2', '4ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Curimataú e Seridó Paraibano', '4', '22', '2', '4ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '23', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '24', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '25', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '26', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Alto Sertão', '8', '27', '3', '8ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '28', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '29', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '30', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '31', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Alto Sertão', '8', '32', '3', '8ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '33', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '34', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '35', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Alto Sertão', '8', '36', '3', '8ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Alto Sertão', '8', '37', '3', '8ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '38', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '39', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '40', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '41', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '42', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '43', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '44', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '45', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '46', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Terra de Maringá', '10', '47', '3', '13ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '48', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '49', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '50', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Mamanguape', '1', '51', '1', '14ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '52', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '53', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '54', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '55', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Alto Sertão', '8', '56', '3', '8ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '57', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '58', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '59', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '60', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '61', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '62', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '63', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '64', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Curimataú e Seridó Paraibano', '4', '65', '2', '4ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Curimataú e Seridó Paraibano', '4', '66', '2', '4ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Mamanguape', '1', '67', '1', '14ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '68', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Mamanguape', '1', '69', '1', '14ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '70', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Curimataú e Seridó Paraibano', '4', '71', '2', '4ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '72', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '73', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '74', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '75', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '76', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values (' Renascer do Brejo', '3', '77', '2', '3ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '78', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Curimataú e Seridó Paraibano', '4', '79', '2', '4ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '80', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '81', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '82', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '83', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '84', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '85', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão da Décima primeira região', '11', '86', '3', '11ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '87', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '88', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '89', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Mamanguape', '1', '90', '1', '14ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '91', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Mamanguape', '1', '92', '1', '14ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Alto Sertão', '8', '93', '3', '8ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '94', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '95', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '96', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '97', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '98', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '99', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão da Décima primeira região', '11', '100', '3', '11ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Terra de Maringá', '10', '101', '3', '13ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '102', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values (' Renascer do Brejo', '3', '103', '2', '3ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale dos Dinossauros', '10', '104', '3', '10ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '105', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '106', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '107', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '108', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '109', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Mamanguape', '1', '110', '1', '14ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão da Décima primeira região', '11', '111', '3', '11ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Mamanguape', '1', '112', '1', '14ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '113', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale dos Dinossauros', '10', '114', '3', '10ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '115', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Mamanguape', '1', '116', '1', '14ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values (' Renascer do Brejo', '3', '117', '2', '3ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Alto Sertão', '8', '118', '3', '8ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '119', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '120', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values (' Renascer do Brejo', '3', '121', '2', '3ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '122', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '123', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '124', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '125', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale dos Dinossauros', '10', '126', '3', '10ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Curimataú e Seridó Paraibano', '4', '127', '2', '4ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '128', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Curimataú e Seridó Paraibano', '4', '129', '2', '4ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '130', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '131', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '132', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '133', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '134', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '135', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Terra de Maringá', '10', '136', '3', '13ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '137', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Curimataú e Seridó Paraibano', '4', '138', '2', '4ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '139', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Mamanguape', '1', '140', '1', '14ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '141', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Curimataú e Seridó Paraibano', '4', '142', '2', '4ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '143', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '144', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '145', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '146', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '147', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '148', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '149', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '150', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Terra de Maringá', '10', '151', '3', '13ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '152', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão da Décima primeira região', '11', '153', '3', '11ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '154', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '155', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '156', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values (' Renascer do Brejo', '3', '157', '2', '3ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '158', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '159', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '160', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '161', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Alto Sertão', '8', '162', '3', '8ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Mamanguape', '1', '163', '1', '14ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '164', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '165', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '166', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale dos Dinossauros', '10', '167', '3', '10ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '168', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '169', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '170', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '171', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '172', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '173', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '174', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '175', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Terra de Maringá', '10', '176', '3', '13ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Alto Sertão', '8', '177', '3', '8ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Terra de Maringá', '10', '178', '3', '13ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '179', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale dos Dinossauros', '10', '180', '3', '10ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '181', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '182', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '183', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale dos Dinossauros', '10', '184', '3', '10ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '185', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '186', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '187', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão da Décima primeira região', '11', '188', '3', '11ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '189', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Alto Sertão', '8', '190', '3', '8ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '191', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '192', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '193', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '194', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale do Paraíba', '12', '195', '1', '12ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values (' Renascer do Brejo', '3', '196', '2', '3ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '197', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Curimataú e Seridó Paraibano', '4', '198', '2', '4ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '199', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '200', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '201', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Vale do Piancó', '7', '202', '3', '7ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '203', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '204', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '205', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Mata Atlântica', '1', '206', '1', '1ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '207', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '208', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Curimataú e Seridó Paraibano', '4', '209', '2', '4ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale dos Dinossauros', '10', '210', '3', '10ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '211', '2', '5ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Piemonte da Borborema', '2', '212', '1', '2ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '213', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão da Décima primeira região', '11', '214', '3', '11ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '215', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Borborema', '3', '216', '2', '16ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '217', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Univale', '9', '218', '3', '9ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Oriental', '3', '219', '2', '15ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '220', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Vale dos Dinossauros', '10', '221', '3', '10ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Sertão Patos', '6', '222', '3', '6ª');
insert into "core_regiao" ("descricao", "gerencia_id", "id", "macrorregiao_id", "nome") values ('Cariri Ocidental', '5', '223', '2', '5ª');
