insert into "core_estado" ("id", "nome", "uf") values ('1', 'Rondônia', 11);
insert into "core_estado" ("id", "nome", "uf") values ('2', 'Acre', 12);
insert into "core_estado" ("id", "nome", "uf") values ('3', 'Amazonas', 13);
insert into "core_estado" ("id", "nome", "uf") values ('4', 'Roraima', 14);
insert into "core_estado" ("id", "nome", "uf") values ('5', 'Pará', 15);
insert into "core_estado" ("id", "nome", "uf") values ('6', 'Amapá', 16);
insert into "core_estado" ("id", "nome", "uf") values ('7', 'Tocantins', 17);
insert into "core_estado" ("id", "nome", "uf") values ('8', 'Maranhão', 21);
insert into "core_estado" ("id", "nome", "uf") values ('9', 'Piauí', 22);
insert into "core_estado" ("id", "nome", "uf") values ('10', 'Ceará', 23);
insert into "core_estado" ("id", "nome", "uf") values ('11', 'Rio Grande do Norte', 24);
insert into "core_estado" ("id", "nome", "uf") values ('12', 'Paraíba', 25);
insert into "core_estado" ("id", "nome", "uf") values ('13', 'Pernambuco', 26);
insert into "core_estado" ("id", "nome", "uf") values ('14', 'Alagoas', 27);
insert into "core_estado" ("id", "nome", "uf") values ('15', 'Sergipe', 28);
insert into "core_estado" ("id", "nome", "uf") values ('16', 'Bahia', 29);
insert into "core_estado" ("id", "nome", "uf") values ('17', 'Minas Gerais', 31);
insert into "core_estado" ("id", "nome", "uf") values ('18', 'Espírito Santo', 32);
insert into "core_estado" ("id", "nome", "uf") values ('19', 'Rio de Janeiro', 33);
insert into "core_estado" ("id", "nome", "uf") values ('20', 'São Paulo', 35);
insert into "core_estado" ("id", "nome", "uf") values ('21', 'Paraná', 41);
insert into "core_estado" ("id", "nome", "uf") values ('22', 'Santa Catarina', 42);
insert into "core_estado" ("id", "nome", "uf") values ('23', 'Rio Grande do Sul', 43);
insert into "core_estado" ("id", "nome", "uf") values ('24', 'Mato Grosso do Sul', 50);
insert into "core_estado" ("id", "nome", "uf") values ('25', 'Mato Grosso', 51);
insert into "core_estado" ("id", "nome", "uf") values ('26', 'Goiás', 52);
insert into "core_estado" ("id", "nome", "uf") values ('27', 'Distrito Federal', 53);
