insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('11', '2500106', '1', 'Água Branca');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2500205', '2', 'Aguiar');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2500304', '3', 'Alagoa Grande');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2500403', '4', 'Alagoa Nova');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2500502', '5', 'Alagoinha');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2500536', '6', 'Alcantil');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2500577', '7', 'Algodão de Jandaíra');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2500601', '8', 'Alhandra');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2500734', '9', 'Amparo');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2500775', '10', 'Aparecida');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2500809', '11', 'Araçagi');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2500908', '12', 'Arara');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2501005', '13', 'Araruna');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2501104', '14', 'Areia');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2501153', '15', 'Areia de Baraúnas');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2501203', '16', 'Areial');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2501302', '17', 'Aroeiras');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2501351', '18', 'Assunção');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2501401', '19', 'Baía da Traição');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2501500', '20', 'Bananeiras');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('4', '2501534', '21', 'Baraúna');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('4', '2501609', '22', 'Barra de Santa Rosa');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2501575', '23', 'Barra de Santana');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2501708', '24', 'Barra de São Miguel');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2501807', '25', 'Bayeux');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2501906', '26', 'Belém');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('8', '2502003', '27', 'Belém do Brejo do Cruz');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2502052', '28', 'Bernardino Batista');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2502102', '29', 'Boa Ventura');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2502151', '30', 'Boa Vista');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2502201', '31', 'Bom Jesus');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('8', '2502300', '32', 'Bom Sucesso');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2502409', '33', 'Bonito de Santa Fé');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2502508', '34', 'Boqueirão');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2502706', '35', 'Borborema');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('8', '2502805', '36', 'Brejo do Cruz');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('8', '2502904', '37', 'Brejo dos Santos');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2503001', '38', 'Caaporã');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2503100', '39', 'Cabaceiras');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2503209', '40', 'Cabedelo');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2503308', '41', 'Cachoeira dos Índios');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2503407', '42', 'Cacimba de Areia');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2503506', '43', 'Cacimba de Dentro');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2503555', '44', 'Cacimbas');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2503605', '45', 'Caiçara');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2503704', '46', 'Cajazeiras');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2503753', '47', 'Cajazeirinhas');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2503803', '48', 'Caldas Brandão');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2503902', '49', 'Camalaú');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2504009', '50', 'Campina Grande');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2504033', '51', 'Capim');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2504074', '52', 'Caraúbas');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2504108', '53', 'Carrapateira');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2504157', '54', 'Casserengue');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2504207', '55', 'Catingueira');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('8', '2504306', '56', 'Catolé do Rocha');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2504355', '57', 'Caturité');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2504405', '58', 'Conceição');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2504504', '59', 'Condado');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2504603', '60', 'Conde');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2504702', '61', 'Congo');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2504801', '62', 'Coremas');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2504850', '63', 'Coxixola');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2504900', '64', 'Cruz do Espírito Santo');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('4', '2505006', '65', 'Cubati');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('4', '2505105', '66', 'Cuité');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2505238', '67', 'Cuité de Mamanguape');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2505204', '68', 'Cuitegi');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2505279', '69', 'Curral de Cima');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2505303', '70', 'Curral Velho');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('4', '2505352', '71', 'Damião');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2505402', '72', 'Desterro');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2505600', '73', 'Diamante');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2505709', '74', 'Dona Inês');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2505808', '75', 'Duas Estradas');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2505907', '76', 'Emas');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2506004', '77', 'Esperança');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2506103', '78', 'Fagundes');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('4', '2506202', '79', 'Frei Martinho');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2506251', '80', 'Gado Bravo');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2506301', '81', 'Guarabira');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2506400', '82', 'Gurinhém');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2506509', '83', 'Gurjão');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2506608', '84', 'Ibiara');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2502607', '85', 'Igaracy');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('11', '2506707', '86', 'Imaculada');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2506806', '87', 'Ingá');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2506905', '88', 'Itabaiana');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2507002', '89', 'Itaporanga');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2507101', '90', 'Itapororoca');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2507200', '91', 'Itatuba');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2507309', '92', 'Jacaraú');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('8', '2507408', '93', 'Jericó');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2507507', '94', 'João Pessoa');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2513653', '95', 'Joca Claudino');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2507606', '96', 'Juarez Távora');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2507705', '97', 'Juazeirinho');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2507804', '98', 'Junco do Seridó');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2507903', '99', 'Juripiranga');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('11', '2508000', '100', 'Juru');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2508109', '101', 'Lagoa');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2508208', '102', 'Lagoa de Dentro');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2508307', '103', 'Lagoa Seca');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2508406', '104', 'Lastro');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2508505', '105', 'Livramento');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2508554', '106', 'Logradouro');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2508604', '107', 'Lucena');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2508703', '108', 'Mãe d''Água');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2508802', '109', 'Malta');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2508901', '110', 'Mamanguape');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('11', '2509008', '111', 'Manaíra');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2509057', '112', 'Marcação');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2509107', '113', 'Mari');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2509156', '114', 'Marizópolis');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2509206', '115', 'Massaranduba');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2509305', '116', 'Mataraca');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2509339', '117', 'Matinhas');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('8', '2509370', '118', 'Mato Grosso');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2509396', '119', 'Maturéia');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2509404', '120', 'Mogeiro');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2509503', '121', 'Montadas');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2509602', '122', 'Monte Horebe');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2509701', '123', 'Monteiro');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2509800', '124', 'Mulungu');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2509909', '125', 'Natuba');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2510006', '126', 'Nazarezinho');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('4', '2510105', '127', 'Nova Floresta');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2510204', '128', 'Nova Olinda');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('4', '2510303', '129', 'Nova Palmeira');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2510402', '130', 'Olho d''Água');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2510501', '131', 'Olivedos');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2510600', '132', 'Ouro Velho');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2510659', '133', 'Parari');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2510709', '134', 'Passagem');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2510808', '135', 'Patos');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2510907', '136', 'Paulista');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2511004', '137', 'Pedra Branca');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('4', '2511103', '138', 'Pedra Lavrada');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2511202', '139', 'Pedras de Fogo');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2512721', '140', 'Pedro Régis');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2511301', '141', 'Piancó');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('4', '2511400', '142', 'Picuí');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2511509', '143', 'Pilar');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2511608', '144', 'Pilões');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2511707', '145', 'Pilõezinhos');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2511806', '146', 'Pirpirituba');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2511905', '147', 'Pitimbu');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2512002', '148', 'Pocinhos');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2512036', '149', 'Poço Dantas');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2512077', '150', 'Poço de José de Moura');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2512101', '151', 'Pombal');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2512200', '152', 'Prata');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('11', '2512309', '153', 'Princesa Isabel');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2512408', '154', 'Puxinanã');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2512507', '155', 'Queimadas');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2512606', '156', 'Quixabá');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2512705', '157', 'Remígio');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2512747', '158', 'Riachão');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2512754', '159', 'Riachão do Bacamarte');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2512762', '160', 'Riachão do Poço');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2512788', '161', 'Riacho de Santo Antônio');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('8', '2512804', '162', 'Riacho dos Cavalos');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2512903', '163', 'Rio Tinto');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2513000', '164', 'Salgadinho');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2513109', '165', 'Salgado de São Félix');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2513158', '166', 'Santa Cecília');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2513208', '167', 'Santa Cruz');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2513307', '168', 'Santa Helena');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2513356', '169', 'Santa Inês');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2513406', '170', 'Santa Luzia');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2513703', '171', 'Santa Rita');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2513802', '172', 'Santa Teresinha');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2513505', '173', 'Santana de Mangueira');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2513604', '174', 'Santana dos Garrotes');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2513851', '175', 'Santo André');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2513927', '176', 'São Bentinho');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('8', '2513901', '177', 'São Bento');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2513968', '178', 'São Domingos');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2513943', '179', 'São Domingos do Cariri');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2513984', '180', 'São Francisco');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2514008', '181', 'São João do Cariri');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2500700', '182', 'São João do Rio do Peixe');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2514107', '183', 'São João do Tigre');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2514206', '184', 'São José da Lagoa Tapada');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2514305', '185', 'São José de Caiana');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2514404', '186', 'São José de Espinharas');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2514503', '187', 'São José de Piranhas');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('11', '2514552', '188', 'São José de Princesa');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2514602', '189', 'São José do Bonfim');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('8', '2514651', '190', 'São José do Brejo do Cruz');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2514701', '191', 'São José do Sabugi');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2514800', '192', 'São José dos Cordeiros');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2514453', '193', 'São José dos Ramos');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2514909', '194', 'São Mamede');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('12', '2515005', '195', 'São Miguel de Taipu');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2515104', '196', 'São Sebastião de Lagoa de Roça');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2515203', '197', 'São Sebastião do Umbuzeiro');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('4', '2515401', '198', 'São Vicente do Seridó');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2515302', '199', 'Sapé');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2515500', '200', 'Serra Branca');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2515609', '201', 'Serra da Raiz');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('7', '2515708', '202', 'Serra Grande');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2515807', '203', 'Serra Redonda');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2515906', '204', 'Serraria');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2515930', '205', 'Sertãozinho');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('1', '2515971', '206', 'Sobrado');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2516003', '207', 'Solânea');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2516102', '208', 'Soledade');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('4', '2516151', '209', 'Sossêgo');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2516201', '210', 'Sousa');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2516300', '211', 'Sumé');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('2', '2516409', '212', 'Tacima');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2516508', '213', 'Taperoá');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('11', '2516607', '214', 'Tavares');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2516706', '215', 'Teixeira');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2516755', '216', 'Tenório');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2516805', '217', 'Triunfo');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('9', '2516904', '218', 'Uiraúna');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('3', '2517001', '219', 'Umbuzeiro');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2517100', '220', 'Várzea');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('10', '2517209', '221', 'Vieirópolis');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('6', '2505501', '222', 'Vista Serrana');
insert into "core_municipio" ("gerencia_id", "ibge", "id", "nome") values ('5', '2517407', '223', 'Zabelê');
